### ISSUE TITLE
How to use fdp-hbreakpoint

### ISSUE THREAD

**Issue by fatgrass** [quarkslab/LLDBagility#17]
I've tried as following:
(lldb) fdp-hbreakpoint set e 0 0xffffff800a4ef167
* Invalid expression
(lldb) fdp-hbreakpoint set e 1 mach_port_insert_right
* Invalid expression

what's the right expression?
Thanks

**Comment by integeruser** [comment]
Hello, you are using `fdp-hbreakpoint` correctly. I think `Invalid expression` happens because you are executing the command while the kernel is running (and not paused in the debugger): 
```
(lldb) fdp-hbreakpoint set e 1 mach_port_insert_right
* Hardware breakpoint set: address = 0xffffff800eda4c20
(lldb) c
Process 1 resuming
(lldb) fdp-hbreakpoint set e 1 mach_port_insert_right
* Invalid expression
```
Could you confirm this is the case? I will then update the README.

**Comment by fatgrass** [comment]
Thanks for your sugesstion.
I tried agian,it really works very good.Rememmber to use fdp-hbreakpoit after fdp-interrupt.
